### ISSUE TITLE
knihovna se neumí připojit/samovolně se odpojuje

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/mtb-net-lib#2]
V případě, že mtb-daemon nmá spojení s mtb-usb deskou tak se knihovna nechce připojit.

Pokud při provozu odpojím mtb-usb (vytáhnu USB kabel), tak se knihovna odpojí od mtb-daemona. Po opětovném zapojení kabelu již hJOP se daemonem nekomunikuje. hJOP se sama po výpadku neobnoví do funkčního stavu.

**Comment by malinajan** [comment]
Automatické obnovení komunikace po výpadku USB kabelu není záměrem. Obnovení funkce hJOPky po výpadku USB vždy provádí obsluha.

**Comment by petrilakm** [comment]
Tak buď bude obsluha potvrzovat každé připojení MTB desky a nebo se vše bude řešit samočinně. Nevím, proč by obsluha měla potvrzovat znovupřipojení k mtb-daemonu. Taky není dobré, že se k němu nedá připojit bez skutečného HW.

**Comment by malinajan** [comment]
Standardně je MTB-USB trvale připojeno, odpojení je porucha. Ty máš potřebu MTB-USB odpojovat?

**Comment by petrilakm** [comment]
Právě proto, že je to porucha, tak je potřeba co nejrychleji obnovit provoz.
Při testování to odpojuji často.

Hlavně mi vadí, že se nedá připojit, bez připojeného HW. Přitom hJOP se má bavit s mtb-daemon a na HW podle mě záviset vůbec nemá.

**Comment by malinajan** [comment]
Např. při ztrátě komunikace s uLI se komunikace taky sama neobnovuje. Momentálně je logika vystavena tak, že otevírání zařízení a spouštění komunikace z pohledu hJOP inicialuzuje vždy hJOP. Idea je, že obsluha potvrdí vyřešení poruchy a je tím vynucena zvýšená pozornost poruše.
